# -*- coding: utf-8 -*-
"""AMZ 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fP9xEQseeZVR2YWeWg1vYcfIE7rFPEyw
"""

number = 0
while number <= 10 :
  print(number, end=" ")
  number += 1

for i in range (1,11):
  print(i, end=',')

number = int(input())
while True:
  if number > 10 and number < 20 :
    print(number)
    if n

import numpy as np
a = np.array([1,2,3,4,5])
rata2 = np.mean(a)
print(int(rata2))

matrix = [
    [5, 5, 8],
    [2, 7, 9],
    [8, 5, 3]
]
determinan = np.linalg.det(matrix)
print(int(determinan))
invers = np.linalg.inv(matrix).astype(int)
print(invers)


#for x in range(0, len(matrix)):
# for y in range(0, len(matrix[0])):
#    print(matrix[x][y], end=" ")

"""1. Untuk mencari determinan

  determinan = np.linalg.det(matrix)
2. Untuk mencari invers

  determinan = np.linalg.inv(matrix)
3. Untuk mencari transpose matrix

  print(np.transpose(matrix))
  
"""

import pandas as pd
a = {"Ganjil" : [1,3,5,7,9], "Genap": [2,4,6,8,10], "Prima":[2,3,5,7,11]}
b = pd.DataFrame(data=a)
count_w=b.shape[1]
print(count_w)
print(b)

"""b.shape[0] : untuk menunjukkan banyak baris

b.shape[1] : untuk menunjukkan banyak kolom
"""

!pip install tabulate==0.8.9

from tabulate import tabulate
import pandas as pd
a = {"Nama" : ["A","B","C"], "Umur": [18,19,20], "Jurusan":["Matematika","Fisika","Kimia"]}
b = pd.DataFrame(data=a)
count=b.shape[1]
print(count)
b.loc[len(b)] = ["D", 21, "Biologi"]
b.loc[len(b)] = ["E", 22, "Statistika"]
print(tabulate(b, tablefmt="grid"))

"""Untuk menambahkan data sebaris, dapat digunakan :

b.loc[len(b)] = ["D", 21, "Biologi"]

print(b)
"""

from tabulate import tabulate
import pandas as pd
a = {"Nama" : ["A","B","C"], "Umur": [18,19,20], "Jurusan":["Matematika","Fisika","Kimia"]}
b = pd.DataFrame(data=a)
count=b.shape[1]
print(count)
b.loc[len(b)] = ["D", 21, "Biologi"]
b.loc[len(b)] = ["E", 22, "Statistika"]
print(tabulate(b, tablefmt="grid"))
column_sum = b['Umur'].sum()
print("Total umur adalah : ",column_sum)