# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UmNdvtce-kL13okFKXYsdcYCSUatLrS
"""

Nama=['nabella agustia','shifa','assyifa', 'intan']
umur=[19, 19, 19, 20]
jurusan=["matematika", "teknik", "kedokteran", "kebidanan"]
print(Nama)
print(umur)
print(jurusan)
del Nama[1]
print(Nama)
Nama.remove('intan')
print(Nama)

import pandas as pd
data={
    'nama': ['Alya', 'budi', 'citra','dimas'],
    'umur': [21,22,20,23],
    'Nilai': [90,88,87,76]
}
df=pd.DataFrame(data)
print(df)

#statistika
print("\nStatistik dasar: ")
print(df.describe())

#menambah kolom baru
df['Kategori Nilai']= df['Nilai'].apply(lambda x: 'Baik' if x>= 85 else 'cukup')
print(df)

#filter data
filtered_data=df[df['Nilai']> 85]
print(filtered_data)

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

#Data contoh
#x adalah variabel bebas, y variabel tak bebas
x=np.array([1,2,3,4,5])
y=np.array([2,4,5,4,5])

x=x.reshape(-1,1)

model=LinearRegression()

model.fit(x,y)

print(f'Koefisien: {model.coef_}')
print(f'Intercept: {model.intercept_}')

y_pred=model.predict(x)

plt.scatter(x,y,color='blue', label='Data Asli')
plt.plot(x,y_pred, color='red', label='Garis Regresi')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()

import statistics
data=[1,2,2,3,4,5,5,5,6,7]

#modus
modus=statistics.mode(data)
print(f'Modus:{modus}')

#median
median=statistics.median(data)
print(f'Median: {median}')

#rata-rata
rata_rata=statistics.mean(data)
print(f'Rata-rata: {rata_rata}')