# -*- coding: utf-8 -*-
"""AMZ 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16N3WOpSvEWs2ycdXqNb2LZC2LpJ1UgyI
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.arange(1,11)
y = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

plt.plot(x,y, marker='o', color='b',label='Angka Prima')
plt.title('Grafik Garis : Angka Prima')
plt.xlabel('Index')
plt.ylabel('Nilai')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

data = np.random.rand(1000)

plt.hist(data, bins=20, color='blue', edgecolor='yellow', alpha=1)
plt.title('Histogram : Distribusi Data Acak')
plt.xlabel('Nilai')
plt.ylabel('Frekuensi')
plt.show

import matplotlib.pyplot as plt

categories = ['A','B','C','D']
values = [3,7,8,5]

plt.bar(categories, values, color=['red','green','blue','orange'])
plt.title('Diagram Batang : Perbandingan Kategori')
plt.xlabel('Kategori')
plt.ylabel('Nilai')
plt.show

import matplotlib.pyplot as plt

labels = ['Apples','Bananas','Cherries','Dates']
sizes = [30,45,15,10]
colors = ['purple','yellow','red','green']

plt.pie(sizes, labels=labels, colors=colors, autopct='%1.f%%', startangle=180)
plt.title('Diagram Lingkaran : Proporsi Buah')
plt.show()

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

colors = list(mcolors.CSS4_COLORS.keys())
print(colors)

import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

data = np.random.rand(10,10)

sns.heatmap(data, annot = True, cmap='coolwarm', linewidths=1)
plt.title('Heatmap : Matriks Data Acak')
plt.show()

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

colors = list(mcolors.CSS4_COLORS.keys())

print(colors)

num_colors = len(colors)
fig, ax = plt.subplots(figsize=(num_colors / 10, 1))  # Adjust figsize as needed
ax.imshow([[(mcolors.to_rgb(color)) for color in colors]], aspect='auto')
ax.set_xticks(range(num_colors))
ax.set_xticklabels(colors, rotation=90, fontsize=8)  # Adjust fontsize as needed
ax.set_yticks([])
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

cmaps = plt.colormaps()

for cmap in cmaps:
    print(cmap)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Load dataset
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target
df['species'] = df['species'].map({0: 'Setosa', 1: 'Versicolor', 2: 'Virginica'})

# 1. Scatter Plot 3D
fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection='3d')

for species in df['species'].unique():
    subset = df[df['species'] == species]
    ax.scatter(subset.iloc[:, 0], subset.iloc[:, 1], subset.iloc[:, 2], label=species, s=50)

ax.set_title('3D Scatter Plot: Iris Dataset')
ax.set_xlabel('Sepal Length (cm)')
ax.set_ylabel('Sepal Width (cm)')
ax.set_zlabel('Petal Length (cm)')
ax.legend()
plt.show()

# 2. Heatmap Korelasi
correlation_matrix = df.iloc[:, :-1].corr()

plt.figure(figsize=(8,6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.1f', linewidths=1)
plt.title('Heatmap Korelasi Fitur')
plt.show()

# 3. Violin Plot
plt.figure(figsize=(10, 6))
sns.violinplot(x='species', y=df.columns[2], data=df, palette='muted')
plt.title('Violin Plot: Petal Length per Species')
plt.xlabel('Species')
plt.ylabel('Petal Length (cm)')
plt.show()