# -*- coding: utf-8 -*-
"""DataSains_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMwgonSpLYdNZbFxAWSjK7GY4wpsmWTj
"""

print ("SAYA LETIH LEMAH LESU")

print("Abel siapa?")

#masukan pada phyton
x = 11
y = 14
z = 15
print (x,y,z)

a = 'rani'
b = 'suka'
c = 'toto'
print(a,b,c)

a=11
print (a)

a = input()
print(a)

a=11
#keluaran phyton yang lebih singkat
print("nilai variabel a = " + str (a))
#keluaran yang rumit
print ("nilai variabel a = {}".format(a))
#keluaran python pakai float
#keluaran python-string
print(f"nilai variabel a = {a}")